# Site settings
title: Unix Solutions Blog
description: Practical Solutions for Unix Problems
baseurl: "/our-blog" # the subpath of your site
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Social links
github_username: tecofers
twitter_username: AliImranMuneeri
linkedin_username: ali-imran-nagori

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
